# Generated by Django 3.2.9 on 2021-12-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211203_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
