# Generated by Django 3.2.9 on 2021-12-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211207_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
